#!/usr/bin/env node
// generate.mjs — generates deploy/compose/docker-compose.netlab.yml from
// NETLAB_* environment variables (defaults for zero-config runs).
//
// Env reference:
//   NETLAB_INSTANCES              number of kesher instances (default 3)
//   NETLAB_DURATION_SECONDS       probe measurement duration (default 30)
//   NETLAB_PORT_BASE              host port of the first instance (default 39080)
//   NETLAB_PROFILE                preset: lan | wifi | wan | worst
//   NETLAB_LATENCY_MS / JITTER_MS / LOSS_PCT / REORDER_PCT / DUPLICATE_PCT / BITRATE_KBIT
//                                 global network profile (per-instance override:
//                                 NETLAB_INSTANCE_<i>_LATENCY_MS etc., i = 1..N)
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const PRESETS = {
  lan: { latencyMs: 5, jitterMs: 2, lossPct: 0, reorderPct: 0, duplicatePct: 0, bitrateKbit: 0 },
  wifi: { latencyMs: 15, jitterMs: 6, lossPct: 0.5, reorderPct: 0, duplicatePct: 0, bitrateKbit: 0 },
  wan: { latencyMs: 60, jitterMs: 15, lossPct: 1, reorderPct: 0.5, duplicatePct: 0, bitrateKbit: 0 },
  worst: { latencyMs: 150, jitterMs: 40, lossPct: 5, reorderPct: 2, duplicatePct: 0.5, bitrateKbit: 512 },
};

const env = process.env;
const preset = PRESETS[String(env.NETLAB_PROFILE || "").toLowerCase()] || {};
const buildTs = new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "").replace("T", "-").replace("Z", "Z");

const num = (key, fallback) => {
  const raw = env[key];
  if (raw === undefined || raw === "") return fallback;
  const n = Number(raw);
  return Number.isFinite(n) ? n : fallback;
};

const instances = Math.max(1, Math.floor(num("NETLAB_INSTANCES", 3)));
const durationSec = Math.max(5, Math.floor(num("NETLAB_DURATION_SECONDS", 30)));
const portBase = Math.floor(num("NETLAB_PORT_BASE", 39080));

const baseProfile = (i) => {
  const prefix = `NETLAB_INSTANCE_${i}_`;
  return {
    latencyMs: num(prefix + "LATENCY_MS", num("NETLAB_LATENCY_MS", preset.latencyMs ?? 20)),
    jitterMs: num(prefix + "JITTER_MS", num("NETLAB_JITTER_MS", preset.jitterMs ?? 8)),
    lossPct: num(prefix + "LOSS_PCT", num("NETLAB_LOSS_PCT", preset.lossPct ?? 1)),
    reorderPct: num(prefix + "REORDER_PCT", num("NETLAB_REORDER_PCT", preset.reorderPct ?? 0)),
    duplicatePct: num(prefix + "DUPLICATE_PCT", num("NETLAB_DUPLICATE_PCT", preset.duplicatePct ?? 0)),
    bitrateKbit: num(prefix + "BITRATE_KBIT", num("NETLAB_BITRATE_KBIT", preset.bitrateKbit ?? 0)),
  };
};

const profileEnv = (p) => [
  `NETLAB_LATENCY_MS: "${p.latencyMs}"`,
  `NETLAB_JITTER_MS: "${p.jitterMs}"`,
  `NETLAB_LOSS_PCT: "${p.lossPct}"`,
  `NETLAB_REORDER_PCT: "${p.reorderPct}"`,
  `NETLAB_DUPLICATE_PCT: "${p.duplicatePct}"`,
  `NETLAB_BITRATE_KBIT: "${p.bitrateKbit}"`,
];

const indent = (lines, n) => lines.map((l) => "  ".repeat(n) + l);

const out = [];
out.push("name: kesher-netlab");
out.push("");
out.push("# Generated by scripts/netlab/generate.mjs — do not edit by hand.");
out.push("# Use: make nettest / make netlab-up / make netlab-down");
out.push("");
out.push("services:");

const instanceNames = [];
for (let i = 1; i <= instances; i++) {
  const name = `instance-${i}`;
  instanceNames.push(name);
  const profile = baseProfile(i);
  const block = [
    `  ${name}:`,
    `    image: kesher-netlab-instance:latest`,
    `    build:`,
    `      context: ../../`,
    `      dockerfile: deploy/docker/Dockerfile.netlab-instance`,
    `      args:`,
    `        VERSION: netlab`,
    `        BUILD_TIMESTAMP: ${buildTs}`,
    `    command: ["/app/server"]`,
    `    environment:`,
    `      APP_ADDR: ":8080"`,
    `      STATIC_DIR: ""`,
    `      DB_PATH: "/app/data/netlab.db"`,
    `      TRUSTED_LAN_HTTP: "true"`,
    `      ALLOW_CORS: "false"`,
    `      SESSION_TTL_MINUTES: "720"`,
    `      LAB_MULTI_SESSION: "true"`,
    `      UDP_AUDIO_ADDR: ":8081"`,
    ...indent(profileEnv(profile), 3),
    `    ports:`,
    `      - "${portBase + i - 1}:8080"`,
    `    volumes:`,
    `      - netlab-data-${i}:/app/data`,
    `    init: true`,
    `    healthcheck:`,
    `      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/api/healthz >/dev/null 2>&1 || exit 1"]`,
    `      interval: 3s`,
    `      timeout: 2s`,
    `      retries: 60`,
    `      start_period: 5s`,
  ];
  out.push(...block);
}

const probeEnv = (i, role, transport, room) => [
  `      PROBE_INSTANCE: "http://${instanceNames[i - 1]}:8080"`,
  `      PROBE_ROLE: "${role}"`,
  `      PROBE_ROLE_ID: "${env.NETLAB_ROLE_ID || "audio"}"`,
  `      PROBE_TRANSPORT: "${transport}"`,
  `      PROBE_ROOM: "${room}"`,
  `      PROBE_DURATION_SECONDS: "${durationSec}"`,
  `      PROBE_NACK: "${env.NETLAB_NACK === "0" ? "0" : "1"}"`,
  `      PROBE_REPORT_DIR: "/out"`,
];

// Each instance runs two isolated transport pairs so WebRTC (browser path)
// and the native UDP relay (Tauri path) can be compared under identical
// network conditions without cross-talk:
//   - probe-<i>-a / probe-<i>-b   on room "foh"   -> WebRTC pair
//   - probe-<i>-a-native / -b-native on room "stage" -> native pair
const transports = [
  { transport: "webrtc", suffix: "", room: env.NETLAB_ROOM_WEBRTC || "foh" },
  { transport: "native", suffix: "-native", room: env.NETLAB_ROOM_NATIVE || "stage" },
];

for (let i = 1; i <= instances; i++) {
  for (const t of transports) {
    for (const role of ["a", "b"]) {
      const name = `probe-${i}-${role}${t.suffix}`;
      const block = [
        `  ${name}:`,
        `    image: kesher-netlab-probe:latest`,
        `    build:`,
        `      context: ../../`,
        `      dockerfile: deploy/docker/Dockerfile.probe`,
        `      args:`,
        `        BUILD_TIMESTAMP: ${buildTs}`,
        `    command: ["/app/probe"]`,
        `    environment:`,
        ...probeEnv(i, role, t.transport, t.room),
        `    volumes:`,
        `      - netlab-reports:/out`,
        `    init: true`,
        `    depends_on:`,
        `      ${instanceNames[i - 1]}:`,
        `        condition: service_healthy`,
        `    restart: "no"`,
      ];
      out.push(...block);
    }
  }
}

out.push("");
out.push("volumes:");
for (let i = 1; i <= instances; i++) {
  out.push(`  netlab-data-${i}:`);
}
out.push("  netlab-reports:");
out.push("");

const target = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "deploy", "compose", "docker-compose.netlab.yml");
writeFileSync(target, out.join("\n"), "utf8");
console.log(`netlab: wrote ${target} (${instances} instances, ${instances * 4} probes [webrtc + native], duration ${durationSec}s)`);
