#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = "remove" ]; then
  systemctl stop kesher-node.service >/dev/null 2>&1 || true
  systemctl disable kesher-node.service >/dev/null 2>&1 || true
fi

exit 0
